// Generated by ConvertDesignTokens on 10/24/25
// DO NOT EDIT MANUALLY

import UIKit

extension UIColor {
  enum Brand {
    /// 메인 브랜드 색상
    static let primary = UIColor(hex: "#574A9FFF")

    /// 연한 브랜드 색상 (보조)
    static let secondary = UIColor(hex: "#ADACC7FF")
  }

  enum Category {
    static let amberGlow = UIColor(hex: "#FEA80EFF")
    static let azureBeam = UIColor(hex: "#11AFFEFF")
    static let brightGreen = UIColor(hex: "#00C950FF")
    static let brightPurple = UIColor(hex: "#BC13FFFF")
    static let brightRed = UIColor(hex: "#FB2C36FF")
    static let charcoalGray = UIColor(hex: "#4A5565FF")
    static let deepBlue = UIColor(hex: "#013CFBFF")
    static let electricSky = UIColor(hex: "#05D6FBFF")
    static let hotFuchsia = UIColor(hex: "#FF05DDFF")
    static let pinkMagenta = UIColor(hex: "#FE0C88FF")
    static let sunnyYellow = UIColor(hex: "#FAD410FF")
    static let vividAmber = UIColor(hex: "#E17100FF")
    static let vividOrange = UIColor(hex: "#FD7304FF")
    static let vividViolet = UIColor(hex: "#AD46FFFF")
  }

  enum Neutral {
    /// 순수한 검정색(기본 텍스트)
    static let black = UIColor(hex: "#000000FF")

    /// 아주 연한 구분선, Placeholder 텍스트
    static let level200 = UIColor(hex: "#C4C4C4FF")

    /// 안내성 텍스트, 메뉴 설명
    static let level300 = UIColor(hex: "#99A1AFFF")

    /// 비활성 상태, 약한 보조 아이콘
    static let level400 = UIColor(hex: "#999999FF")

    /// 보조 정보 텍스트
    static let level600 = UIColor(hex: "#757575FF")

    /// 중간 중요도 텍스트
    static let level800 = UIColor(hex: "#364153FF")

    /// 순수한 흰색 (배경, 본문 등)
    static let white = UIColor(hex: "#FFFFFFFF")
  }

  enum Opacity {
    /// 검정색 30% 투명도
    static let black30 = UIColor(hex: "#0000004D")

    /// 흰색 75% 투명도
    static let white75 = UIColor(hex: "#FFFFFFBF")
  }

  enum Status {
    /// 쥐소/약한 경고
    static let cancel = UIColor(hex: "#F44366FF")

    /// 경고/오류 아이콘 색상
    static let danger = UIColor(hex: "#E7000BFF")

    /// 지출, 위험 상태
    static let expense = UIColor(hex: "#FF0000FF")

    /// 수입, 긍정적 상태, 활성 상태
    static let income = UIColor(hex: "#0090FFFF")

    /// 정보 강조 아이콘 색상
    static let info = UIColor(hex: "#155DFCFF")

    /// 활성/강조/주요 상호작용
    static let interactive = UIColor(hex: "#2B7FFFFF")
  }

  enum Surface {
    /// 위험/경고 정보 아이콘의 연한 배경색
    static let dangerLight = UIColor(hex: "#FEF2F2FF")

    /// 일반 정보 아이콘의 연한 배경색
    static let infoLight = UIColor(hex: "#EFF6FFFF")

    /// 메인 화면의 기본 배경색
    static let primary = UIColor(hex: "#FAFAFAFF")

    /// 모달이나 보조 컨텐츠 영역의 배경색
    static let secondary = UIColor(hex: "#F4F4F4FF")
  }
}
